// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveSelfArgs {
    pub direction_x: f32,
    pub direction_y: f32,
    pub delta_seconds: f32,
}

impl From<MoveSelfArgs> for super::Reducer {
    fn from(args: MoveSelfArgs) -> Self {
        Self::MoveSelf {
            direction_x: args.direction_x,
            direction_y: args.direction_y,
            delta_seconds: args.delta_seconds,
        }
    }
}

impl __sdk::InModule for MoveSelfArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_self`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_self {
    /// Request that the remote module invoke the reducer `move_self` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_self:move_self_then`] to run a callback after the reducer completes.
    fn move_self(
        &self,
        direction_x: f32,
        direction_y: f32,
        delta_seconds: f32,
    ) -> __sdk::Result<()> {
        self.move_self_then(direction_x, direction_y, delta_seconds, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_self` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_self_then(
        &self,
        direction_x: f32,
        direction_y: f32,
        delta_seconds: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_self for super::RemoteReducers {
    fn move_self_then(
        &self,
        direction_x: f32,
        direction_y: f32,
        delta_seconds: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            MoveSelfArgs {
                direction_x,
                direction_y,
                delta_seconds,
            },
            callback,
        )
    }
}
