// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub id: u64,
    pub identity: __sdk::Identity,
    pub connection_id: __sdk::ConnectionId,
    pub name: String,
    pub x: f32,
    pub y: f32,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub id: __sdk::__query_builder::Col<Player, u64>,
    pub identity: __sdk::__query_builder::Col<Player, __sdk::Identity>,
    pub connection_id: __sdk::__query_builder::Col<Player, __sdk::ConnectionId>,
    pub name: __sdk::__query_builder::Col<Player, String>,
    pub x: __sdk::__query_builder::Col<Player, f32>,
    pub y: __sdk::__query_builder::Col<Player, f32>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            connection_id: __sdk::__query_builder::Col::new(table_name, "connection_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub connection_id: __sdk::__query_builder::IxCol<Player, __sdk::ConnectionId>,
    pub id: __sdk::__query_builder::IxCol<Player, u64>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            connection_id: __sdk::__query_builder::IxCol::new(table_name, "connection_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
