// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_type::Player;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `players_snapshot`.
///
/// Obtain a handle from the [`PlayersSnapshotTableAccess::players_snapshot`] method on [`super::RemoteTables`],
/// like `ctx.db.players_snapshot()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players_snapshot().on_insert(...)`.
pub struct PlayersSnapshotTableHandle<'ctx> {
    imp: __sdk::TableHandle<Player>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `players_snapshot`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayersSnapshotTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayersSnapshotTableHandle`], which mediates access to the table `players_snapshot`.
    fn players_snapshot(&self) -> PlayersSnapshotTableHandle<'_>;
}

impl PlayersSnapshotTableAccess for super::RemoteTables {
    fn players_snapshot(&self) -> PlayersSnapshotTableHandle<'_> {
        PlayersSnapshotTableHandle {
            imp: self.imp.get_table::<Player>("players_snapshot"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayersSnapshotInsertCallbackId(__sdk::CallbackId);
pub struct PlayersSnapshotDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayersSnapshotTableHandle<'ctx> {
    type Row = Player;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Player> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayersSnapshotInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersSnapshotInsertCallbackId {
        PlayersSnapshotInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayersSnapshotInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayersSnapshotDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersSnapshotDeleteCallbackId {
        PlayersSnapshotDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayersSnapshotDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Player>("players_snapshot");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Player>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Player>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Player`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait players_snapshotQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Player`.
    fn players_snapshot(&self) -> __sdk::__query_builder::Table<Player>;
}

impl players_snapshotQueryTableAccess for __sdk::QueryTableAccessor {
    fn players_snapshot(&self) -> __sdk::__query_builder::Table<Player> {
        __sdk::__query_builder::Table::new("players_snapshot")
    }
}
